# EDA

Names: Alex Sheardown, Nathan Nishi, Joshua Palicka

First we are going to load in our data.

In [1]:
import pandas as pd
import numpy as np

shark_data_unclean = pd.read_csv('Data/data_adding_more_weather_version_3_alex.csv',encoding = "ISO-8859-1")

shark_data_unclean = shark_data_unclean.drop("Unnamed: 0.1.1" , 1)
shark_data_unclean = shark_data_unclean.drop("Unnamed: 0.1" , 1)
shark_data_unclean = shark_data_unclean.drop("Date" , 1)
for number in range(0, 300):
    try:
        shark_data_unclean = shark_data_unclean.drop("Unnamed: " + str(number) , axis=1)
    except:
        x = 0

<ipython-input-1-cc73641a6fd1>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Unnamed: 0.1.1" , 1)
<ipython-input-1-cc73641a6fd1>:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Unnamed: 0.1" , 1)
<ipython-input-1-cc73641a6fd1>:8: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Date" , 1)

Next, we're looking at the columns to see if there are any that we don't need. It looks like there are some columns that won't add anything to our analysis, like "Year" -- as the year is already included in "Date". We drop the columns we won't use.

In [2]:
shark_data_unclean.columns

Index(['Type', 'Activity', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Proper_date', 'Full Location', 'latitude', 'longitude',
       'avg_temp', 'precipitation', 'wind_speed', 'sea_level_pressure'],
      dtype='object')

In [3]:
try:
    shark_data_unclean = shark_data_unclean.drop("pdf" , 1)
    shark_data_unclean = shark_data_unclean.drop("href formula" , 1)
    shark_data_unclean = shark_data_unclean.drop("href" , 1)
    shark_data_unclean = shark_data_unclean.drop("Year" , 1)
    shark_data_unclean = shark_data_unclean.drop("Investigator or Source" , 1)
    shark_data_unclean = shark_data_unclean.drop("original order" , 1)
    shark_data_unclean = shark_data_unclean.drop("Name" , 1)
    shark_data_unclean = shark_data_unclean.drop("Date" , 1)
except:
        x = 0

shark_data_unclean

<ipython-input-3-e45be0a08bd8>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("pdf" , 1)

,Type,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Proper_date,Full Location,latitude,longitude,avg_temp,precipitation,wind_speed,sea_level_pressure
0,Unprovoked,surfing,M,6.0,Minor injury to right arm,N,1320,Not Determined,20210909.0,"USA Florida Ponce Inlet, Volusia County",29.096373,-80.936998,26.1,1.0,16.2,1012.5
1,Unprovoked,surfing,M,31.0,FATAL,Y,1030,White xhark,20210905.0,AUSTRALIA New South Wales Emerald Beach,-30.157479,153.150195,13.6,4.6,20.4,1017.3
2,Unprovoked,boarding,M,NaN,Lacerations both sides of lower leg immediatel...,N,1145,Not Determined,20210828.0,"USA Texas Galveston Island, Galveston County",29.241005,-94.909133,29.4,2.5,10.4,1013.7
3,Unprovoked,fell,M,64.0,Severe injury to leg,N,1400,Not Determined,20210903.0,USA Louisiana off Grand Isle,29.236617,-89.987294,27.2,3.9,5.1,1014.6
4,Unprovoked,surfing,M,41.0,Left ankle and foot bitten,N,0640,Bull shark,20210821.0,"USA Florida Walton Beach Psrk, St. Lucie County",27.337890,-80.233431,28.9,0.2,11.0,1015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4131,Unprovoked,floating,M,NaN,"Bathing suit torn & ""imprints of the shark's t...",N,1800,Not Determined,19000905.0,"USA Hawaii Waikiki Beach, Oahu",21.279346,-157.829185,NaN,NaN,NaN,NaN
4132,Unprovoked,bathing,M,NaN,Left hand lacerated,N,1800,Not Determined,19000821.0,"USA North Carolina Southport, Brunswick County",33.918209,-78.019301,NaN,NaN,NaN,NaN
4133,Unprovoked,swimming,M,NaN,FATAL,Y,9999,Not Determined,19000731.0,"CROATIA Primorje-Gorski Kotar County Volosko,...",45.350000,14.316667,NaN,NaN,NaN,NaN
4134,Provoked,NaN,Not Determined,NaN,"No injury to occupants. They shot shark, then ...",N,9999,Not Determined,NaN,"USA Connecticut Bridgeport, Fairfield County",41.179226,-73.189438,NaN,NaN,NaN,NaN
4135,Unprovoked,NaN,M,NaN,Right posterior thigh bitten,N,1200,Not Determined,NaN,"AUSTRALIA New South Wales Lane Cove River, Syd...",-33.782705,151.140035,NaN,NaN,NaN,NaN

Next, we're taking a look at the value counts of the "Type" column. These correspond to the type of attack. The most common are Unprovoked, Provoked, and Invalid, although Watercraft and Sea Disaster are there too. We mainly want to look at provoked and unprovoked. 

We drop the rows that have Na types

In [4]:
#shark_data_unclean.value_counts("Type")

shark_data_unclean.dtypes

Type                   object
Activity               object
Sex                    object
Age                   float64
Injury                 object
Fatal (Y/N)            object
Time                   object
Species                object
Proper_date           float64
Full Location          object
latitude              float64
longitude             float64
avg_temp              float64
precipitation         float64
wind_speed            float64
sea_level_pressure    float64
dtype: object

In [5]:
shark_data_unclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4136 entries, 0 to 4135
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Type                4136 non-null   object
 1   Activity            3973 non-null   object
 2   Sex                 4136 non-null   object
 3   Age                 2950 non-null   float64
 4   Injury              4136 non-null   object
 5   Fatal (Y/N)         4136 non-null   object
 6   Time                4136 non-null   object
 7   Species             4136 non-null   object
 8   Proper_date         3749 non-null   float64
 9   Full Location       4136 non-null   object
 10  latitude            4136 non-null   float64
 11  longitude           4136 non-null   float64
 12  avg_temp            1699 non-null   float64
 13  precipitation       2144 non-null   float64
 14  wind_speed          1452 non-null   float64
 15  sea_level_pressure  962 non-null    float64
dtypes: float64(8), object(8)
memory usage: 517.1+ KB

In [6]:
#shark_data_unclean = shark_data_unclean.dropna(how='all')
#shark_data_unclean = shark_data_unclean.dropna(thresh=3)
#shark_data_unclean = shark_data_unclean[shark_data_unclean['Type'].notna()]
#df.dropna(thresh=2)
#shark_data_unclean

Now that we don't have to deal with 30K Na rows, the dataset looks a little more manageable. The next step here is to clean the 'Date' column, so we create a new column called 'Proper_date' which is easier to manage.

In [7]:
shark_data_unclean['Time'] = shark_data_unclean['Time'].replace(regex='([a-zA-Z])', value=0)
shark_data_unclean['Time'] = shark_data_unclean['Time'].fillna(0)
#shark_data_unclean['Time'] = shark_data_unclean['Time'].astype(int)

#Activity
shark_data_unclean['Activity'] = shark_data_unclean['Activity'].fillna(0)

#Proper Date
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].fillna(0)
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].astype('int')


shark_data_date = shark_data_unclean[shark_data_unclean['Proper_date'] > 19000000] 
average = int(shark_data_date["Proper_date"].mean())
shark_data_unclean["Proper_date"].replace({0: average}, inplace=True)
print(average)

#Age
shark_data_unclean['Age'] = shark_data_unclean['Age'].fillna(0)
shark_data_unclean['Age'] = shark_data_unclean['Age'].astype('int')


shark_data_date = shark_data_unclean[shark_data_unclean['Age'] > 0] 
average = int(shark_data_date["Age"].mean())
shark_data_unclean["Age"].replace({0: average}, inplace=True)
print(average)


#avg_temp
shark_data_unclean['avg_temp'] = shark_data_unclean['avg_temp'].fillna(0)
#shark_data_unclean['avg_temp'] = shark_data_unclean['avg_temp'].astype('int')


shark_data_date = shark_data_unclean[shark_data_unclean['avg_temp'] > 0] 
average = shark_data_date["avg_temp"].mean()
shark_data_unclean["avg_temp"].replace({0: average}, inplace=True)
print(average)


#precipitation
shark_data_unclean['precipitation'] = shark_data_unclean['precipitation'].fillna(0)
#shark_data_unclean['precipitation'] = shark_data_unclean['precipitation'].astype('int')


shark_data_date = shark_data_unclean[shark_data_unclean['precipitation'] > 0] 
average = shark_data_date["precipitation"].mean()
shark_data_unclean["precipitation"].replace({0: average}, inplace=True)
print(average)


#wind_speed
shark_data_unclean['wind_speed'] = shark_data_unclean['wind_speed'].fillna(0)
#shark_data_unclean['wind_speed'] = shark_data_unclean['wind_speed'].astype('int')


shark_data_date = shark_data_unclean[shark_data_unclean['wind_speed'] > 0] 
average = shark_data_date["wind_speed"].mean()
shark_data_unclean["wind_speed"].replace({0: average}, inplace=True)
print(average)


#sea_level_pressure
shark_data_unclean['sea_level_pressure'] = shark_data_unclean['sea_level_pressure'].fillna(0)
#shark_data_unclean['sea_level_pressure'] = shark_data_unclean['sea_level_pressure'].astype('int')


shark_data_date = shark_data_unclean[shark_data_unclean['sea_level_pressure'] > 0] 
average = shark_data_date["sea_level_pressure"].mean()
shark_data_unclean["sea_level_pressure"].replace({0: average}, inplace=True)
print(average)
shark_data_unclean

19875253
27
24.041155660377356
9.165705614567528
12.665633608815426
1016.2291060291059

,Type,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Proper_date,Full Location,latitude,longitude,avg_temp,precipitation,wind_speed,sea_level_pressure
0,Unprovoked,surfing,M,6,Minor injury to right arm,N,1320,Not Determined,20210909,"USA Florida Ponce Inlet, Volusia County",29.096373,-80.936998,26.100000,1.000000,16.200000,1012.500000
1,Unprovoked,surfing,M,31,FATAL,Y,1030,White xhark,20210905,AUSTRALIA New South Wales Emerald Beach,-30.157479,153.150195,13.600000,4.600000,20.400000,1017.300000
2,Unprovoked,boarding,M,27,Lacerations both sides of lower leg immediatel...,N,1145,Not Determined,20210828,"USA Texas Galveston Island, Galveston County",29.241005,-94.909133,29.400000,2.500000,10.400000,1013.700000
3,Unprovoked,fell,M,64,Severe injury to leg,N,1400,Not Determined,20210903,USA Louisiana off Grand Isle,29.236617,-89.987294,27.200000,3.900000,5.100000,1014.600000
4,Unprovoked,surfing,M,41,Left ankle and foot bitten,N,0640,Bull shark,20210821,"USA Florida Walton Beach Psrk, St. Lucie County",27.337890,-80.233431,28.900000,0.200000,11.000000,1015.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4131,Unprovoked,floating,M,27,"Bathing suit torn & ""imprints of the shark's t...",N,1800,Not Determined,19000905,"USA Hawaii Waikiki Beach, Oahu",21.279346,-157.829185,24.041156,9.165706,12.665634,1016.229106
4132,Unprovoked,bathing,M,27,Left hand lacerated,N,1800,Not Determined,19000821,"USA North Carolina Southport, Brunswick County",33.918209,-78.019301,24.041156,9.165706,12.665634,1016.229106
4133,Unprovoked,swimming,M,27,FATAL,Y,9999,Not Determined,19000731,"CROATIA Primorje-Gorski Kotar County Volosko,...",45.350000,14.316667,24.041156,9.165706,12.665634,1016.229106
4134,Provoked,0,Not Determined,27,"No injury to occupants. They shot shark, then ...",N,9999,Not Determined,19875253,"USA Connecticut Bridgeport, Fairfield County",41.179226,-73.189438,24.041156,9.165706,12.665634,1016.229106
4135,Unprovoked,0,M,27,Right posterior thigh bitten,N,1200,Not Determined,19875253,"AUSTRALIA New South Wales Lane Cove River, Syd...",-33.782705,151.140035,24.041156,9.165706,12.665634,1016.229106

Alex took some time to clean the date column here.

In [8]:

shark_data_unclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4136 entries, 0 to 4135
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Type                4136 non-null   object
 1   Activity            4136 non-null   object
 2   Sex                 4136 non-null   object
 3   Age                 4136 non-null   int64
 4   Injury              4136 non-null   object
 5   Fatal (Y/N)         4136 non-null   object
 6   Time                4136 non-null   object
 7   Species             4136 non-null   object
 8   Proper_date         4136 non-null   int64
 9   Full Location       4136 non-null   object
 10  latitude            4136 non-null   float64
 11  longitude           4136 non-null   float64
 12  avg_temp            4136 non-null   float64
 13  precipitation       4136 non-null   float64
 14  wind_speed          4136 non-null   float64
 15  sea_level_pressure  4136 non-null   float64
dtypes: float64(6), int64(2), object(8)
memory usage: 517.1+ KB

Because our project is trying to determine if a shark attack is provoked or unprovoked, we drop the rows which don't strictly contain "Provoked" or "Unprovoked"

In [9]:
#shark_data_unclean['Type'].isna("Invalid")
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Invalid"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Watercraft"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Boat"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Unconfirmed"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Unverified"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Under investigation"]

#Might need to be changed to Provoked
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Sea Disaster"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Questionable"]

shark_data_unclean["Type"].value_counts()

Unprovoked    3696
Provoked       440
Name: Type, dtype: int64

There's a column determining if a shark attack was fatal or not. This needed to be cleaned.

In [10]:
shark_data_unclean['Fatal (Y/N)'] = shark_data_unclean['Fatal (Y/N)'].str.replace(" N", 'N')
shark_data_unclean['Fatal (Y/N)'] = shark_data_unclean['Fatal (Y/N)'].str.replace("N ", 'N')
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "UNKNOWN"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "Not Determined"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "Nq"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "M"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "2017"]



shark_data_unclean["Fatal (Y/N)"].value_counts()

N    3426
Y     710
Name: Fatal (Y/N), dtype: int64

Again, Alex did a bunch of data cleaning. This time on the 'Time' column.

In [11]:
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Afternoon", '18h00')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Lunchtime", '12h00')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("\"Early evening\"", '17h00')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("j", 'h')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("h", '')

shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1016", '1000')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Before 0700", '0600')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1000 -- 1100", '1000')

shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("`", '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0900-1000", '0900')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Morning", '0800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Evening", '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Midday", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Early ", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1800"', '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Before 1000", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1200afternoon", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1400  -1500", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Late afternoon", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1900, Dusk", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Nigt", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sortly before 1200", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("After noon", '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1430 / 1530", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0930 / 1000", '1000')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sometime between 0600 & 08oo", '0700')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0700 - 0800", '0730')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1815-1830", '1830')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0900 - 0930", '0930')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just before noon", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("AM", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("A.M.", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Dusk", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1200morning", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just before 1100", '1100')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1100"', '1100')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sunset", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just before sundown", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1700 or 1740", '1700')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(">0800", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("--", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just after 1200", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(" ", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sortly9999after9999midnigt", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("09009999-1000", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("20459999(9999)", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('(', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(')', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Late9999morning', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Sortly9999before99991300', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('8:049999pm', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Late9999morning', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('After99999999', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Noon', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('P.M.', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('29999ours9999after9999Opperman', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('11009999/99991130', '1130')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1500"', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1830?', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1500"', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1500?', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('?', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('309999minutes9999after99991992.07.08.a', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>0645', '0630')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Between999906009999&99990720', '0730')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('<0730', '0730')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>0645', '0630')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('X', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Prior9999to99991037', '1030')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Daybreak', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>1200', '1230')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Mid-morning', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('16309999or99991800', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('10009999/99991100', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('15009999or99991545', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('19009999/99992000', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Dawn', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12459999/999913450', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12459999/99991345', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('14009999-99991500', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('nigt', '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('09309999/99991530', '1530')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12459999/99991345', '1400')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('08009999/99990930', '0930')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('10309999or99991330', '1330')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('.', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"After9999dark"', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('10009999or99991400', '1000')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('29999rs9999before9999sunset', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>1430', '1430')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('After9999dusk', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('FATAL99999999Wire9999netting9999installed9999at9999local9999beaces9999after9999tis9999incident', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('After9999mid1800', '2400')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Late9999afternon', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1319', '1330')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1928', '1930')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1421', '1430')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12000800', '9999')

<ipython-input-11-745a861ef82b>:34: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("A.M.", '9999')
<ipython-input-11-745a861ef82b>:48: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("20459999(9999)", '9999')
<ipython-input-11-745a861ef82b>:49: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('(', '')
<ipython-input-11-745a861ef82b>:50: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(')', '')
<ipython-input-11-745a861ef82b>:57: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('P.M.', '9999')
<ipython-input-11-745a861ef82b>:61: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1830?', '1500')
<ipython-input-11-745a861ef82b>:63: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1500?', '1500')
<ipython-input-11-745a861ef82b>:64: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('?', '')
<ipython-input-11-745a861ef82b>:65: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('309999minutes9999after99991992.07.08.a', '9999')
<ipython-input-11-745a861ef82b>:88: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('.', '')

In [12]:
shark_data_unclean.to_csv('Data/Alex_Kinda_clean_data.csv')