Names: Alex Sheardown

In [549]:
import pandas as pd
import numpy as np
shark_data_unclean = pd.read_csv('Data/GSAF5.csv',encoding = "ISO-8859-1")

shark_data_unclean = shark_data_unclean.drop("Unnamed: 246" , 1)


for number in range(1, 300):
    try:
        shark_data_unclean = shark_data_unclean.drop("Unnamed: " + str(number) , axis=1)
    except:
        x = 0



shark_data_unclean.columns

C:\Users\alexa\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3418: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-549-fbdc6ef3c2e1>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Unnamed: 246" , 1)

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [550]:
shark_data_unclean = shark_data_unclean.drop("pdf" , 1)
shark_data_unclean = shark_data_unclean.drop("href formula" , 1)
shark_data_unclean = shark_data_unclean.drop("href" , 1)
shark_data_unclean = shark_data_unclean.drop("Year" , 1)
shark_data_unclean = shark_data_unclean.drop("Investigator or Source" , 1)
shark_data_unclean = shark_data_unclean.drop("original order" , 1)
shark_data_unclean = shark_data_unclean.drop("Name" , 1)
shark_data_unclean

<ipython-input-550-aaa4274a57cb>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("pdf" , 1)
<ipython-input-550-aaa4274a57cb>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("href formula" , 1)
<ipython-input-550-aaa4274a57cb>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("href" , 1)
<ipython-input-550-aaa4274a57cb>:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Year" , 1)
<ipython-input-550-aaa4274a57cb>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Investigator or Source" , 1)
<ipython-input-550-aaa4274a57cb>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("original order" , 1)
<ipython-input-550-aaa4274a57cb>:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Name" , 1)

,Case Number,Date,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Case Number.1,Case Number.2
0,2021.09.10,10-Sep-2021,NaN,EGYPT,NaN,Sidi Abdel Rahmen,Swimming,M,NaN,Laceration to arm caused by metal object,NaN,NaN,No shark invovlement,2021.09.10,2021.09.10
1,2021.09.09,09-Sep-2021,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,M,!6,Minor injury to right arm,N,13h20,NaN,2021.09.09,2021.09.09
2,2021.09.05,05-Sep-2021,Unprovoked,AUSTRALIA,New South Wales,Emerald Beach,Surfing,M,31,FATAL,Y,10h30,White xhark,2021.09.05,2021.09.05
3,2021.09.03.b,03-Sep-2021,Unprovoked,British Overseas Territory,Turks and Caicos,NaN,NaN,M,NaN,Wrist bitten,N,NaN,NaN,2021.09.03.b,2021.09.03.b
4,2021.08.28,28-Aug-2021,Unprovoked,USA,Texas,"Galveston Island, Galveston County",Boogie boarding,M,!!,Lacerations both sides of lower leg immediatel...,N,11h45,NaN,2021.08.28,2021.08.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [551]:
#shark_data_unclean = shark_data_unclean.dropna(how='all')
shark_data_unclean = shark_data_unclean.dropna(thresh=3)
shark_data_unclean = shark_data_unclean[shark_data_unclean['Type'].notna()]
#df.dropna(thresh=2)
shark_data_unclean

,Case Number,Date,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Case Number.1,Case Number.2
1,2021.09.09,09-Sep-2021,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,M,!6,Minor injury to right arm,N,13h20,NaN,2021.09.09,2021.09.09
2,2021.09.05,05-Sep-2021,Unprovoked,AUSTRALIA,New South Wales,Emerald Beach,Surfing,M,31,FATAL,Y,10h30,White xhark,2021.09.05,2021.09.05
3,2021.09.03.b,03-Sep-2021,Unprovoked,British Overseas Territory,Turks and Caicos,NaN,NaN,M,NaN,Wrist bitten,N,NaN,NaN,2021.09.03.b,2021.09.03.b
4,2021.08.28,28-Aug-2021,Unprovoked,USA,Texas,"Galveston Island, Galveston County",Boogie boarding,M,!!,Lacerations both sides of lower leg immediatel...,N,11h45,NaN,2021.08.28,2021.08.28
5,2021.09.03,03-Sep-2021,Unprovoked,USA,Louisiana,off Grand Isle,"Fishing, fell in water",M,64,Severe injury to leg,N,14h00,NaN,2021.09.03,2021.09.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6695,ND.0005,Before 1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,M,NaN,FATAL,Y,NaN,NaN,ND.0005,ND.0005
6696,ND.0004,Before 1903,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,M,NaN,FATAL,Y,NaN,NaN,ND.0004,ND.0004
6697,ND.0003,1900-1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,NaN,FATAL,Y,NaN,NaN,ND.0003,ND.0003
6698,ND.0002,1883-1889,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,M,NaN,FATAL,Y,NaN,NaN,ND.0002,ND.0002
6699,ND.0001,1845-1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,ND.0001,ND.0001

In [552]:
#shark_data_unclean["Case Number"] = shark_data_unclean["Case Number"]
shark_data_unclean['Proper_date'] = shark_data_unclean['Case Number'].str.replace(".", '')

shark_data_unclean

<ipython-input-552-133eca060277>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Proper_date'] = shark_data_unclean['Case Number'].str.replace(".", '')

,Case Number,Date,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Case Number.1,Case Number.2,Proper_date
1,2021.09.09,09-Sep-2021,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,M,!6,Minor injury to right arm,N,13h20,NaN,2021.09.09,2021.09.09,20210909
2,2021.09.05,05-Sep-2021,Unprovoked,AUSTRALIA,New South Wales,Emerald Beach,Surfing,M,31,FATAL,Y,10h30,White xhark,2021.09.05,2021.09.05,20210905
3,2021.09.03.b,03-Sep-2021,Unprovoked,British Overseas Territory,Turks and Caicos,NaN,NaN,M,NaN,Wrist bitten,N,NaN,NaN,2021.09.03.b,2021.09.03.b,20210903b
4,2021.08.28,28-Aug-2021,Unprovoked,USA,Texas,"Galveston Island, Galveston County",Boogie boarding,M,!!,Lacerations both sides of lower leg immediatel...,N,11h45,NaN,2021.08.28,2021.08.28,20210828
5,2021.09.03,03-Sep-2021,Unprovoked,USA,Louisiana,off Grand Isle,"Fishing, fell in water",M,64,Severe injury to leg,N,14h00,NaN,2021.09.03,2021.09.03,20210903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6695,ND.0005,Before 1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,M,NaN,FATAL,Y,NaN,NaN,ND.0005,ND.0005,ND0005
6696,ND.0004,Before 1903,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,M,NaN,FATAL,Y,NaN,NaN,ND.0004,ND.0004,ND0004
6697,ND.0003,1900-1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,NaN,FATAL,Y,NaN,NaN,ND.0003,ND.0003,ND0003
6698,ND.0002,1883-1889,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,M,NaN,FATAL,Y,NaN,NaN,ND.0002,ND.0002,ND0002
6699,ND.0001,1845-1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,ND.0001,ND.0001,ND0001

In [553]:
#shark_data_unclean['Case Number'].equals(shark_data_unclean['Case Number.1'])
shark_data_unclean['Case Number'].equals(shark_data_unclean['Case Number.2'])

comparison = shark_data_unclean.apply(lambda row: all(i in shark_data_unclean['Case Number'] for i in shark_data_unclean['Case Number.1']), axis=1)
comparison.value_counts()

False    6685
dtype: int64

In [554]:
comparison = shark_data_unclean.apply(lambda row: all(i in shark_data_unclean['Case Number'] for i in shark_data_unclean['Case Number.2']), axis=1)
comparison.value_counts()

False    6685
dtype: int64

In [555]:
shark_data_unclean = shark_data_unclean.drop("Case Number" , 1)
shark_data_unclean = shark_data_unclean.drop("Case Number.1" , 1)
shark_data_unclean = shark_data_unclean.drop("Case Number.2" , 1)

<ipython-input-555-fd4739889cdc>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Case Number" , 1)
<ipython-input-555-fd4739889cdc>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Case Number.1" , 1)
<ipython-input-555-fd4739889cdc>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  shark_data_unclean = shark_data_unclean.drop("Case Number.2" , 1)

In [556]:


shark_data_unclean = shark_data_unclean[shark_data_unclean["Proper_date"].str.contains("ND") == False]
shark_data_unclean = shark_data_unclean[shark_data_unclean["Proper_date"].str.contains("BC") == False]
shark_data_unclean = shark_data_unclean[shark_data_unclean["Proper_date"].str.contains("R") == False]
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("a", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("b", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("c", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("d", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("e", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("f", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("g", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("h", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("i", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("j", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("k", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("l", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("m", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("n", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("o", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("p", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("q", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("r", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("s", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("t", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("u", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("v", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("w", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("x", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("y", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("z", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace(" ", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("0", '0')




#shark_data_unclean = shark_data_unclean[shark_data_unclean["Proper_date"].str.contains("00000") == False]

shark_data_unclean

,Date,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Proper_date
1,09-Sep-2021,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,M,!6,Minor injury to right arm,N,13h20,NaN,20210909
2,05-Sep-2021,Unprovoked,AUSTRALIA,New South Wales,Emerald Beach,Surfing,M,31,FATAL,Y,10h30,White xhark,20210905
3,03-Sep-2021,Unprovoked,British Overseas Territory,Turks and Caicos,NaN,NaN,M,NaN,Wrist bitten,N,NaN,NaN,20210903
4,28-Aug-2021,Unprovoked,USA,Texas,"Galveston Island, Galveston County",Boogie boarding,M,!!,Lacerations both sides of lower leg immediatel...,N,11h45,NaN,20210828
5,03-Sep-2021,Unprovoked,USA,Louisiana,off Grand Isle,"Fishing, fell in water",M,64,Severe injury to leg,N,14h00,NaN,20210903
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Ca. 1554,Unprovoked,FRANCE,Nice & Marseilles,NaN,NaN,M,NaN,NaN,UNKNOWN,NaN,Possibly white sharks,15540000
6566,Ca. 1543,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,M,NaN,FATAL,Y,NaN,NaN,15430000
6567,Ca 1200-1500 A.D.,Unprovoked,MEXICO,NaN,NaN,NaN,M,NaN,Foot severed,N,NaN,NaN,15000000
6568,Ca.789-1033 A.D,Unprovoked,USA,Puerto Rico,Archeological site,NaN,M,29,FATAL,N,NaN,Tiger shark,12000000
6569,Ca. 77 A.D.,Unprovoked,NaN,Ionian Sea,NaN,Sponge diving,M,NaN,FATAL,Y,NaN,NaN,00770000

In [557]:
#This value count raises question about how reliable our data will be.
shark_data_unclean["Type"].value_counts()

Unprovoked             4427
Provoked                543
Invalid                 476
Watercraft              300
Sea Disaster            213
Questionable             12
Boat                      6
Unconfirmed               1
Unverified                1
Under investigation       1
Name: Type, dtype: int64

In [558]:
#Remove ambigous dates
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("-", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("x", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("/", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace(",", '')
shark_data_unclean['Proper_date'] = shark_data_unclean['Proper_date'].str.replace("&", '')




 
shark_data_unclean["Proper_date"] = shark_data_unclean["Proper_date"].astype(int)
shark_data_unclean = shark_data_unclean[shark_data_unclean['Proper_date'] > 19000000]

In [559]:
shark_data_unclean = shark_data_unclean[shark_data_unclean['Country'].notna()]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Area'].notna()]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Location'].notna()]
shark_data_unclean['Time'].fillna("9999", inplace = True)
shark_data_unclean['Activity'].fillna("No Activity", inplace = True)
shark_data_unclean['Age'].fillna("Not Determined", inplace = True)
shark_data_unclean['Fatal (Y/N)'].fillna("Not Determined", inplace = True)
shark_data_unclean['Sex '].fillna("Not Determined", inplace = True)

shark_data_unclean['Injury'].fillna("Not Determined", inplace = True)
shark_data_unclean['Species '].fillna("Not Determined", inplace = True)

shark_data_unclean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5084 entries, 1 to 5952
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         5084 non-null   object
 1   Type         5084 non-null   object
 2   Country      5084 non-null   object
 3   Area         5084 non-null   object
 4   Location     5084 non-null   object
 5   Activity     5084 non-null   object
 6   Sex          5084 non-null   object
 7   Age          5084 non-null   object
 8   Injury       5084 non-null   object
 9   Fatal (Y/N)  5084 non-null   object
 10  Time         5084 non-null   object
 11  Species      5084 non-null   object
 12  Proper_date  5084 non-null   int32
dtypes: int32(1), object(12)
memory usage: 536.2+ KB

In [560]:
#shark_data_unclean['Type'].isna("Invalid")
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Invalid"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Watercraft"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Boat"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Unconfirmed"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Unverified"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Under investigation"]

#Might need to be changed to Provoked
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Sea Disaster"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Questionable"]

shark_data_unclean["Type"].value_counts()

Unprovoked    3855
Provoked       470
Name: Type, dtype: int64

In [561]:
shark_data_unclean['Fatal (Y/N)'] = shark_data_unclean['Fatal (Y/N)'].str.replace(" N", 'N')
shark_data_unclean['Fatal (Y/N)'] = shark_data_unclean['Fatal (Y/N)'].str.replace("N ", 'N')
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "UNKNOWN"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "Not Determined"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "Nq"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "M"]
shark_data_unclean = shark_data_unclean[shark_data_unclean['Fatal (Y/N)'] != "2017"]



shark_data_unclean["Fatal (Y/N)"].value_counts()

N    3529
Y     746
Name: Fatal (Y/N), dtype: int64

In [562]:
#Condensed
#shark_data_unclean['Injury'] = shark_data_unclean['Injury'].str.replace("Left foot bitten", 'Foot bitten')
#shark_data_unclean['Injury'] = shark_data_unclean['Injury'].str.replace("Left foot bitten", 'Foot bitten')
#shark_data_unclean['Injury'] = shark_data_unclean['Injury'].str.replace("No injury, knocked off board, shark bit board", 'No injury')
shark_data_unclean["Injury"].value_counts()

FATAL                                                  385
Foot bitten                                             83
Survived                                                69
Leg bitten                                              57
Left foot bitten                                        50
                                                      ...
Speared shark bit his chest PROVOKED INCIDENT            1
No injury, knocked off board, shark bit board            1
Right thigh & ankle injured                              1
No injury. Towed by speared shark PROVOKED INCIDENT      1
Right posterior thigh bitten                             1
Name: Injury, Length: 2616, dtype: int64

In [563]:
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Afternoon", '18h00')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Lunchtime", '12h00')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("\"Early evening\"", '17h00')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("j", 'h')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("h", '')

shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1016", '1000')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Before 0700", '0600')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1000 -- 1100", '1000')

shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("`", '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0900-1000", '0900')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Morning", '0800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Evening", '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Midday", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Early ", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1800"', '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Before 1000", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1200afternoon", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1400  -1500", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Late afternoon", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1900, Dusk", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Nigt", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sortly before 1200", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("After noon", '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1430 / 1530", '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0930 / 1000", '1000')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sometime between 0600 & 08oo", '0700')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0700 - 0800", '0730')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1815-1830", '1830')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("0900 - 0930", '0930')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just before noon", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("AM", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("A.M.", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Dusk", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1200morning", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just before 1100", '1100')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1100"', '1100')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sunset", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just before sundown", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("1700 or 1740", '1700')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(">0800", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("--", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Just after 1200", '1200')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(" ", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("Sortly9999after9999midnigt", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("09009999-1000", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("20459999(9999)", '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('(', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(')', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Late9999morning', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Sortly9999before99991300', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('8:049999pm', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Late9999morning', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('After99999999', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Noon', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('P.M.', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('29999ours9999after9999Opperman', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('11009999/99991130', '1130')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1500"', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1830?', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"1500"', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1500?', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('?', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('309999minutes9999after99991992.07.08.a', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>0645', '0630')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Between999906009999&99990720', '0730')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('<0730', '0730')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>0645', '0630')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('X', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Prior9999to99991037', '1030')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Daybreak', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>1200', '1230')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Mid-morning', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('16309999or99991800', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('10009999/99991100', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('15009999or99991545', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('19009999/99992000', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Dawn', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12459999/999913450', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12459999/99991345', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('14009999-99991500', '1500')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('nigt', '1800')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('09309999/99991530', '1530')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('12459999/99991345', '1400')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('08009999/99990930', '0930')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('10309999or99991330', '1330')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('.', '')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('"After9999dark"', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('10009999or99991400', '1000')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('29999rs9999before9999sunset', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('>1430', '1430')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('After9999dusk', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('FATAL99999999Wire9999netting9999installed9999at9999local9999beaces9999after9999tis9999incident', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('After9999mid1800', '2400')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('Late9999afternon', '9999')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1319', '1330')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1928', '1930')
shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1421', '1430')

<ipython-input-563-72307a84e65d>:34: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("A.M.", '9999')
<ipython-input-563-72307a84e65d>:48: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace("20459999(9999)", '9999')
<ipython-input-563-72307a84e65d>:49: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('(', '')
<ipython-input-563-72307a84e65d>:50: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace(')', '')
<ipython-input-563-72307a84e65d>:57: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('P.M.', '9999')
<ipython-input-563-72307a84e65d>:61: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1830?', '1500')
<ipython-input-563-72307a84e65d>:63: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('1500?', '1500')
<ipython-input-563-72307a84e65d>:64: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('?', '')
<ipython-input-563-72307a84e65d>:65: FutureWarning: The default value of regex will change from True to False in a future version.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('309999minutes9999after99991992.07.08.a', '9999')
<ipython-input-563-72307a84e65d>:88: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  shark_data_unclean['Time'] = shark_data_unclean['Time'].str.replace('.', '')

In [564]:
"""
shark_data_unclean = shark_data_unclean[shark_data_unclean['Proper_date'].len < 10] 
shark_data_unclean["Time"] = shark_data_unclean["Time"].astype(int)
shark_data_unclean["Time"].value_counts()
shark_data_unclean = shark_data_unclean[shark_data_unclean['Proper_date'] < 2400] 
print(shark_data_unclean["Proper_date"].mean())

"""
shark_data_unclean

,Date,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Proper_date
1,09-Sep-2021,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,M,!6,Minor injury to right arm,N,1320,Not Determined,20210909
2,05-Sep-2021,Unprovoked,AUSTRALIA,New South Wales,Emerald Beach,Surfing,M,31,FATAL,Y,1030,White xhark,20210905
4,28-Aug-2021,Unprovoked,USA,Texas,"Galveston Island, Galveston County",Boogie boarding,M,!!,Lacerations both sides of lower leg immediatel...,N,1145,Not Determined,20210828
5,03-Sep-2021,Unprovoked,USA,Louisiana,off Grand Isle,"Fishing, fell in water",M,64,Severe injury to leg,N,1400,Not Determined,20210903
6,21-Aug-2021,Unprovoked,USA,Florida,"Walton Beach Psrk, St. Lucie County",Surfing,M,41,Left ankle and foot bitten,N,0640,Bull shark,20210821
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5947,05-Sep-1900,Unprovoked,USA,Hawaii,"Waikiki Beach, Oahu",Floating,M,Not Determined,"Bathing suit torn & ""imprints of the shark's t...",N,1800,Not Determined,19000905
5948,21-Aug-1900,Unprovoked,USA,North Carolina,"Southport, Brunswick County",Bathing,M,Not Determined,Left hand lacerated,N,1800,Not Determined,19000821
5949,31-Jul-1900,Unprovoked,CROATIA,Primorje-Gorski Kotar County,"Volosko, Opatija",Swimming,M,Not Determined,FATAL,Y,9999,Not Determined,19000731
5951,Late Jul-1900,Provoked,USA,Connecticut,"Bridgeport, Fairfield County",,Not Determined,Not Determined,"No injury to occupants. They shot shark, then ...",N,9999,Not Determined,19000700
5952,28-Jan-1900,Unprovoked,AUSTRALIA,New South Wales,"Lane Cove River, Sydney Harbor (Estuary)","Standing, gathering oysters",M,Not Determined,Right posterior thigh bitten,N,1200,Not Determined,19000128

In [565]:
#shark_data_unclean['Type'].isna("Invalid")
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Invalid"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Watercraft"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Boat"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Unconfirmed"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Unverified"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Under investigation"]

#Might need to be changed to Provoked
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Sea Disaster"]
shark_data_unclean = shark_data_unclean[shark_data_unclean.Type != "Questionable"]

shark_data_unclean["Type"].value_counts()

Unprovoked    3811
Provoked       464
Name: Type, dtype: int64